// src/components/GuideView.tsx
import { Award, ShieldAlert, BookOpen, Terminal, CheckCircle2 } from 'lucide-react';

export default function GuideView() {
  return (
    <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 space-y-8 h-[calc(100vh-140px)] min-h-[500px] overflow-y-auto max-w-5xl mx-auto">
      {/* Page Title */}
      <div className="border-b border-slate-800 pb-4 flex items-center gap-2.5">
        <Award className="w-6 h-6 text-cyan-400" />
        <div>
          <h3 className="font-semibold text-slate-100 text-base">Cybersecurity Portfolio Triage Guide</h3>
          <p className="text-xs text-slate-400 mt-0.5">How Tier 2 SOC Analysts deploy and run this tool in production environments.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* Left Column: Playbook Workflow */}
        <div className="space-y-5">
          <div className="flex items-center gap-2 text-cyan-400">
            <BookOpen className="w-4 h-4" />
            <h4 className="text-sm font-semibold uppercase tracking-wider text-xs">Real-World Operational Strategy</h4>
          </div>

          <div className="space-y-4 text-xs text-slate-300 leading-relaxed">
            <div className="space-y-1">
              <h5 className="font-semibold text-slate-200 flex items-center gap-1.5">
                <span className="h-1.5 w-1.5 rounded-full bg-cyan-500" />
                1. Automated SIEM Triggering
              </h5>
              <p className="text-slate-400 pl-3">
                Security Information and Event Management (SIEM) consoles aggregate logs across routers, active directories, and firewalls. Analysts deploy this Python script as an automated Cron Job or Serverless Cloud Function (AWS Lambda / Google Cloud Function) to query indices every 5 minutes and alert on stateful sliding window anomalies.
              </p>
            </div>

            <div className="space-y-1">
              <h5 className="font-semibold text-slate-200 flex items-center gap-1.5">
                <span className="h-1.5 w-1.5 rounded-full bg-cyan-500" />
                2. Forensic Endpoint Triage
              </h5>
              <p className="text-slate-400 pl-3">
                During active Incident Response (IR) engagements, networks are often segmented or shut down, isolating infected devices. Analysts load this lightweight script onto an isolated workstation via a USB/bastion drive. Running the tool locally extracts event logs and maps compromised admin users without contacting cloud-based SIEM servers.
              </p>
            </div>

            <div className="space-y-1">
              <h5 className="font-semibold text-slate-200 flex items-center gap-1.5">
                <span className="h-1.5 w-1.5 rounded-full bg-cyan-500" />
                3. Automated SOAR Containment
              </h5>
              <p className="text-slate-400 pl-3">
                The machine-readable **`soc_incident_report.json`** output generated by this script contains strict, structured schemas. SOAR platforms (like Cortex XSOAR) ingest this JSON to automatically orchestrate containment playbooks—such as calling webhooks to revoke user authentication tokens in Okta, locking accounts in Active Directory, or pushing blocking rules to perimeter firewalls.
              </p>
            </div>
          </div>
        </div>

        {/* Right Column: Key Design Choices */}
        <div className="space-y-5">
          <div className="flex items-center gap-2 text-cyan-400">
            <Terminal className="w-4 h-4" />
            <h4 className="text-sm font-semibold uppercase tracking-wider text-xs">Architectural Design Rationale</h4>
          </div>

          <div className="space-y-4 text-xs text-slate-300 leading-relaxed">
            <div className="bg-slate-950/50 p-4 border border-slate-800 rounded-xl space-y-2">
              <h5 className="font-bold text-slate-200 flex items-center gap-1 text-xs">
                <ShieldAlert className="w-4 h-4 text-rose-500" />
                Heuristic Statefulness (VS Static grep)
              </h5>
              <p className="text-slate-400 text-[11px] leading-relaxed">
                Standard firewalls fail to understand sequential behavior. For example, five failed logins are normal user behavior, and a single successful login is standard. This tool correlates them **statefully**: it flags the failed login cluster coming from a *single* IP, checks if it's succeeded by a successful logon, and dynamically raises the severity to **CRITICAL (Risk 95)** because it signifies a confirmed breached identity perimeter.
              </p>
            </div>

            <div className="bg-slate-950/50 p-4 border border-slate-800 rounded-xl space-y-2">
              <h5 className="font-bold text-slate-200 flex items-center gap-1 text-xs">
                <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                Zero-Dependency Portability
              </h5>
              <p className="text-slate-400 text-[11px] leading-relaxed">
                By choosing to write this tool entirely with **pure Python standard libraries** (`csv`, `json`, `datetime`, `re`), we ensure that it can execute on any operating system immediately (Windows Server, Linux servers, macOS) without installing pip packages, compiling binary libraries, or making external API calls that could expose sensitive logs.
              </p>
            </div>
          </div>
        </div>

      </div>

      {/* MITRE ATT&CK Info banner */}
      <div className="p-4 bg-slate-950/30 border border-slate-800 rounded-xl text-xs text-slate-400 leading-relaxed">
        <strong className="text-slate-200 block mb-1">🛡️ MITRE ATT&CK Matrix Techniques Highlighted:</strong>
        <ul className="list-disc pl-5 space-y-1 mt-1 text-slate-400 text-[11px]">
          <li><strong>T1110 (Brute Force)</strong>: Password guessing and password spraying to gain access.</li>
          <li><strong>T1078 (Valid Accounts)</strong>: Authenticating with breached credentials, highlighted via Impossible Travel.</li>
          <li><strong>T1053 (Scheduled Task/Job)</strong>: Executing automated scripts, highlighted via unusual off-hours activities.</li>
          <li><strong>T1548 (Abuse Privilege Escalation Mechanism)</strong>: Attempting local file access or sudo bypass to escalate permissions.</li>
        </ul>
      </div>
    </div>
  );
}
